import type { CaseStudy, ExamplePoster, PricingTier, SocialLink, UseCase } from "@aips/types"

export const SITE = {
  name: "AI Poster Studio",
  tagline: "I gave an AI agent a 19-page research paper and asked for one slide.",
  description:
    "Upload any research paper. An autonomous agent reads, plans, drafts, critiques, and iterates — producing a beautiful, editable research poster in minutes.",
  url: "https://aiposter.studio",
  ogImage: "/og.png",
  author: "Simranjeet Singh",
} as const

export const SOCIAL_LINKS: SocialLink[] = [
  { label: "LinkedIn", href: "https://www.linkedin.com/in/simranjeet97/", handle: "@simranjeet97" },
  {
    label: "Instagram",
    href: "https://www.instagram.com/itsexceptional/",
    handle: "@itsexceptional",
  },
  { label: "GitHub", href: "https://github.com/simranjeet97", handle: "@simranjeet97" },
  { label: "TopMate", href: "https://topmate.io/simranjeet97/", handle: "@simranjeet97" },
]

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "free",
    name: "Free",
    priceMonthly: 0,
    priceAnnualMonthly: 0,
    features: [
      "Unlimited posters (local-first)",
      "4K PNG and vector PDF export",
      "No watermark",
      "All templates",
      "Local LLM via Ollama (no API key)",
      "Community support",
    ],
    limits: {
      postersPerMonth: Number.POSITIVE_INFINITY,
      seats: 1,
      apiAccess: false,
      watermark: false,
    },
    stripePriceId: null,
    featured: false,
  },
  {
    id: "pro",
    name: "Pro (coming soon)",
    priceMonthly: 19,
    priceAnnualMonthly: 15,
    features: [
      "Everything in Free, plus:",
      "Cloud LLM fallback when Ollama is unavailable",
      "Cloud-based poster rendering for sharing",
      "Edit-in-browser poster editor",
      "Priority email support",
    ],
    limits: {
      postersPerMonth: Number.POSITIVE_INFINITY,
      seats: 1,
      apiAccess: false,
      watermark: false,
    },
    stripePriceId: null,
    featured: true,
  },
  {
    id: "lab",
    name: "Lab (coming soon)",
    priceMonthly: 99,
    priceAnnualMonthly: 79,
    features: [
      "Everything in Pro, plus:",
      "5 team seats",
      "Shared workspace",
      "API access",
      "Custom branded templates",
    ],
    limits: {
      postersPerMonth: Number.POSITIVE_INFINITY,
      seats: 5,
      apiAccess: true,
      watermark: false,
    },
    stripePriceId: null,
    featured: false,
  },
]

export const USE_CASES: UseCase[] = [
  {
    id: "researchers",
    title: "For Researchers",
    description:
      "Turn a finished paper into a conference poster in minutes. Spend your time on the science, not on layout.",
    audience: "PhD candidates, postdocs, faculty",
    tint: "lavender",
    icon: "flask",
  },
  {
    id: "students",
    title: "For PhD Students",
    description:
      "Defend your thesis with a poster that actually communicates your contribution clearly.",
    audience: "PhD candidates preparing defenses",
    tint: "mint",
    icon: "graduation",
  },
  {
    id: "organizers",
    title: "For Conference Organizers",
    description:
      "Run poster sessions with consistent quality. Standardize your conference brand across hundreds of posters.",
    audience: "Conference chairs, program committees",
    tint: "sky",
    icon: "calendar",
  },
  {
    id: "journalists",
    title: "For Science Journalists",
    description:
      "Translate dense papers into visual stories your audience can grasp in 30 seconds.",
    audience: "Writers, science communicators",
    tint: "peach",
    icon: "newspaper",
  },
  {
    id: "educators",
    title: "For Educators",
    description:
      "Build teaching posters from seminal papers. Bring research into the classroom visually.",
    audience: "Professors, TAs, curriculum designers",
    tint: "rose",
    icon: "book",
  },
  {
    id: "grants",
    title: "For Grant Writers",
    description:
      "Reuse your paper's content for grant applications and progress reports. One source, many artifacts.",
    audience: "Grant writers, research administrators",
    tint: "yellow",
    icon: "briefcase",
  },
]

export const EXAMPLE_POSTERS: ExamplePoster[] = [
  {
    id: "attention-is-all-you-need",
    title: "Attention Is All You Need",
    paperTitle: "Attention Is All You Need",
    paperArxivId: "1706.03762",
    authors: ["Vaswani et al."],
    field: "ai-ml",
    previewUrl: "/examples/attention.svg",
    posterUrl: "/examples/attention-full.svg",
    draftCount: 4,
    timeMinutes: 3,
    featured: true,
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    paperTitle: "BERT",
    paperArxivId: "1810.04805",
    authors: ["Devlin et al."],
    field: "ai-ml",
    previewUrl: "/examples/bert.svg",
    posterUrl: "/examples/bert-full.svg",
    draftCount: 3,
    timeMinutes: 4,
    featured: true,
  },
  {
    id: "resnet",
    title: "Deep Residual Learning for Image Recognition",
    paperTitle: "ResNet",
    paperArxivId: "1512.03385",
    authors: ["He et al."],
    field: "ai-ml",
    previewUrl: "/examples/resnet.svg",
    posterUrl: "/examples/resnet-full.svg",
    draftCount: 3,
    timeMinutes: 3,
    featured: false,
  },
  {
    id: "alphafold",
    title: "Highly Accurate Protein Structure Prediction with AlphaFold",
    paperTitle: "AlphaFold",
    paperArxivId: "2103.03175",
    authors: ["Jumper et al."],
    field: "biomedicine",
    previewUrl: "/examples/alphafold.svg",
    posterUrl: "/examples/alphafold-full.svg",
    draftCount: 5,
    timeMinutes: 6,
    featured: true,
  },
  {
    id: "gpt-3",
    title: "Language Models are Few-Shot Learners",
    paperTitle: "GPT-3",
    paperArxivId: "2005.14165",
    authors: ["Brown et al."],
    field: "ai-ml",
    previewUrl: "/examples/gpt3.svg",
    posterUrl: "/examples/gpt3-full.svg",
    draftCount: 4,
    timeMinutes: 4,
    featured: false,
  },
  {
    id: "dall-e",
    title: "Zero-Shot Text-to-Image Generation",
    paperTitle: "DALL-E",
    paperArxivId: "2102.12092",
    authors: ["Ramesh et al."],
    field: "ai-ml",
    previewUrl: "/examples/dalle.svg",
    posterUrl: "/examples/dalle-full.svg",
    draftCount: 3,
    timeMinutes: 3,
    featured: false,
  },
  {
    id: "climate-1",
    title: "Observed Changes in the Earth Energy Imbalance",
    paperTitle: "Earth Energy Imbalance",
    paperArxivId: "2103.09357",
    authors: ["Hansen et al."],
    field: "climate",
    previewUrl: "/examples/climate.svg",
    posterUrl: "/examples/climate-full.svg",
    draftCount: 4,
    timeMinutes: 5,
    featured: false,
  },
  {
    id: "physics-1",
    title: "Detection of Gravitational Waves",
    paperTitle: "LIGO Detection",
    paperArxivId: "1602.03837",
    authors: ["Abbott et al."],
    field: "physics",
    previewUrl: "/examples/ligo.svg",
    posterUrl: "/examples/ligo-full.svg",
    draftCount: 4,
    timeMinutes: 5,
    featured: false,
  },
  {
    id: "med-1",
    title: "mRNA Vaccines for Infectious Diseases",
    paperTitle: "mRNA Vaccines",
    paperArxivId: "2101.05739",
    authors: ["Pardi et al."],
    field: "biomedicine",
    previewUrl: "/examples/mrna.svg",
    posterUrl: "/examples/mrna-full.svg",
    draftCount: 3,
    timeMinutes: 4,
    featured: false,
  },
  {
    id: "econ-1",
    title: "Universal Basic Income and Labor Supply",
    paperTitle: "UBI Study",
    paperArxivId: "",
    authors: ["Various"],
    field: "economics",
    previewUrl: "/examples/ubi.svg",
    posterUrl: "/examples/ubi-full.svg",
    draftCount: 3,
    timeMinutes: 4,
    featured: false,
  },
  {
    id: "diffusion",
    title: "Denoising Diffusion Probabilistic Models",
    paperTitle: "DDPM",
    paperArxivId: "2006.11239",
    authors: ["Ho et al."],
    field: "ai-ml",
    previewUrl: "/examples/diffusion.svg",
    posterUrl: "/examples/diffusion-full.svg",
    draftCount: 4,
    timeMinutes: 4,
    featured: false,
  },
  {
    id: "vit",
    title: "An Image is Worth 16x16 Words",
    paperTitle: "Vision Transformer",
    paperArxivId: "2010.11929",
    authors: ["Dosovitskiy et al."],
    field: "ai-ml",
    previewUrl: "/examples/vit.svg",
    posterUrl: "/examples/vit-full.svg",
    draftCount: 3,
    timeMinutes: 3,
    featured: false,
  },
]

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: "neurips-2026",
    slug: "neurips-2026-submission",
    title: "How Dr. Maya cut her NeurIPS poster prep from 8 hours to 12 minutes",
    subtitle: "A computer vision researcher on her second NeurIPS submission",
    authorName: "Dr. Maya Chen",
    authorRole: "Postdoc, Stanford AI Lab",
    authorAvatar: null,
    body: "I used to spend an entire Saturday wrestling with PowerPoint — moving text boxes by 2 pixels at a time, fixing overflow, swapping figures. With AI Poster Studio I uploaded my final preprint, went to make coffee, and came back to a polished poster I could actually edit. The 'Why this design?' feature is what sold me: when my advisor asked why the results panel was bigger, I clicked it and the answer explained the layout decision.",
    posterPreviewUrl: "/examples/attention.svg",
    stats: [
      { label: "Time saved", value: "8 hours → 12 min" },
      { label: "Iterations", value: "4 drafts" },
      { label: "Advisor rounds", value: "1" },
    ],
    publishedAt: "2026-08-15",
  },
  {
    id: "ml-lab",
    slug: "y-lab-50-papers",
    title: "How a research lab standardized 50 conference posters in a week",
    subtitle: "Y Combinator Research's summer cohort",
    authorName: "Jordan Park",
    authorRole: "Lab Director, Y Research",
    authorAvatar: null,
    body: "Every summer our 50 interns present posters at the cohort demo day. Last year we had a beautiful mess of mismatched templates. This year everyone used AI Poster Studio with our custom Lab template. Consistent brand, faster turnaround, happier interns. We even got the institution's design team to approve it as an official tool.",
    posterPreviewUrl: "/examples/bert.svg",
    stats: [
      { label: "Posters generated", value: "50" },
      { label: "Time per poster", value: "avg 4 min" },
      { label: "Templates standardized", value: "3" },
    ],
    publishedAt: "2026-07-20",
  },
  {
    id: "journalism",
    slug: "the-atlantic-explainer",
    title: "From arXiv to reader in 30 minutes: AI-assisted science explainers",
    subtitle: "A science editor's workflow",
    authorName: "Priya Iyer",
    authorRole: "Senior Editor, The Atlantic Science",
    authorAvatar: null,
    body: "When a paper breaks, we need visuals fast. AI Poster Studio lets me pull a figure-rich poster from the original paper, then I edit the captions and abstract panel for our lay audience. The provenance links mean I can verify every claim visually — a huge win for editorial accuracy.",
    posterPreviewUrl: "/examples/alphafold.svg",
    stats: [
      { label: "Time to publish visual", value: "30 min" },
      { label: "Editor hours saved per piece", value: "3+" },
      { label: "Audience engagement", value: "+42%" },
    ],
    publishedAt: "2026-06-10",
  },
]

export const FAQ = [
  {
    question: "How long does it take to generate a poster?",
    answer:
      "Most posters are ready in 2–5 minutes. The agent runs 3–5 revision turns, each taking 30–60 seconds, with critic feedback between turns.",
  },
  {
    question: "Can I edit the poster after it's generated?",
    answer:
      "Yes. Every poster is editable HTML/CSS, not a flat image. Pro and Lab tiers can edit in-browser with our visual editor.",
  },
  {
    question: "What paper formats are supported?",
    answer:
      "Any PDF up to 50MB. We extract text, figures, tables, and equations, and preserve provenance links back to the source pages.",
  },
  {
    question: "Is my paper data private?",
    answer:
      "Yes. Your papers are stored in your private account and never shared or used for training. You can delete everything anytime.",
  },
  {
    question: "What templates are available?",
    answer:
      "CVPR (landscape and portrait), ICML, NeurIPS, Nature, and a custom template. Lab tier can add custom branded templates.",
  },
  {
    question: "Can I use Ollama or a local LLM?",
    answer:
      "Pro tier supports Ollama for the planning LLM. The poster design still uses our hosted coding agent for quality, but you can bring your own model for everything else.",
  },
] as const

export const COMPARISON = [
  {
    feature: "Time to first poster",
    aips: "2–5 minutes",
    canva: "30–60 minutes",
    beautiful: "20–40 minutes",
    designer: "2–4 hours",
  },
  {
    feature: "Auto-extracts from PDF",
    aips: true,
    canva: false,
    beautiful: false,
    designer: false,
  },
  {
    feature: "AI critique + iteration",
    aips: true,
    canva: false,
    beautiful: false,
    designer: false,
  },
  {
    feature: "Editable artifact (HTML, not PNG)",
    aips: true,
    canva: false,
    beautiful: false,
    designer: false,
  },
  {
    feature: "Provenance links to paper",
    aips: true,
    canva: false,
    beautiful: false,
    designer: false,
  },
  {
    feature: "Research-specific templates",
    aips: true,
    canva: false,
    beautiful: true,
    designer: true,
  },
  {
    feature: "Why this design? explanations",
    aips: true,
    canva: false,
    beautiful: false,
    designer: true,
  },
] as const
