import { CTABanner } from "@/components/marketing/cta-banner"
import { EXAMPLE_POSTERS } from "@/lib/data"

export const metadata = {
  title: "Examples",
  description: "Posters generated by AI Poster Studio from real arXiv papers.",
}

const FIELD_LABELS = {
  "ai-ml": "AI / ML",
  biomedicine: "Biomedicine",
  climate: "Climate",
  economics: "Economics",
  physics: "Physics",
  other: "Other",
} as const

export default function ExamplesPage() {
  return (
    <>
      <section className="section-rhythm">
        <div className="mx-auto max-w-marketing px-6">
          <div className="text-center">
            <p className="text-caption-uppercase text-accent">Examples</p>
            <h1 className="mt-3 text-hero text-fg">Posters from real papers.</h1>
            <p className="mx-auto mt-6 max-w-xl text-lead text-fg-2">
              Every poster on this page was generated from the linked arXiv paper in 2–5 minutes.
            </p>
          </div>

          <div className="mt-12 flex flex-wrap items-center justify-center gap-2">
            {Object.entries(FIELD_LABELS).map(([key, label]) => (
              <button
                type="button"
                key={key}
                className="rounded-pill border border-border bg-surface px-4 py-1.5 text-sm text-fg-2 transition-colors hover:bg-surface-warm"
              >
                {label}
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="pb-24">
        <div className="mx-auto max-w-marketing px-6">
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {EXAMPLE_POSTERS.map((poster) => (
              <article
                key={poster.id}
                className="group overflow-hidden rounded-lg border border-border bg-surface transition-shadow hover:shadow-elevated"
              >
                <div className="aspect-[3/4] bg-surface-warm" />
                <div className="p-5">
                  <span className="text-caption-uppercase text-accent">
                    {FIELD_LABELS[poster.field]}
                  </span>
                  <h3 className="mt-2 text-base font-semibold text-fg group-hover:text-accent">
                    {poster.title}
                  </h3>
                  <p className="mt-1 text-sm text-fg-2">{poster.authors.join(", ")}</p>
                  {poster.paperArxivId && (
                    <p className="mt-1 font-mono text-xs text-muted">arXiv:{poster.paperArxivId}</p>
                  )}
                  <div className="mt-4 flex items-center justify-between border-t border-border-soft pt-3 text-xs text-muted">
                    <span>{poster.draftCount} drafts</span>
                    <span>{poster.timeMinutes} min</span>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <CTABanner />
    </>
  )
}
