/**
 * Reasoning engine for "Why this design?" popovers.
 *
 * Given the click data from the poster (data-panel-* attributes) and the
 * full content brief + plan, produce a plain-English explanation of why
 * the agent designed this particular element the way it did.
 */

import type { ContentBrief } from "./ingest"
import type { PosterPlan } from "./plan"

type PanelAttrs = Record<string, string>

export function explainPanel(
  attrs: PanelAttrs,
  brief: ContentBrief | null,
  plan: PosterPlan | null,
): { title: string; body: string } {
  const type = attrs["data-panel-type"] ?? "unknown"

  switch (type) {
    case "title":
      return {
        title: "Title",
        body: "Used the paper title verbatim. Set at 36px / weight 700 with the accent color underline. At A0 scale the title needs to be readable from 3 meters away — anything smaller gets lost.",
      }
    case "tagline":
      return {
        title: "Tagline",
        body: `Generated by Ollama (local LLM) as a 1-sentence summary. Skipped if Ollama isn't running — falls back to no tagline.`,
      }
    case "abstract":
      return {
        title: "Abstract",
        body: `Truncated the paper's abstract to 600 characters. Placed in a tinted band with a thick left border in the accent color so reviewers can scan the core contribution in 10 seconds without reading the whole poster.`,
      }
    case "section": {
      const title = attrs["data-section-title"] ?? "Section"
      const idx = Number.parseInt(attrs["data-section-index"] ?? "0", 10)
      const isMethod = /method|approach|model|architecture/i.test(title)
      const isResults = /result|experiment|evaluation|benchmark/i.test(title)
      const position = idx === 0 ? "first" : idx === 1 ? "second" : "later"
      return {
        title: `${title} section`,
        body: isMethod
          ? `Allocated this panel to the Method section because it's the paper's primary contribution. Placed in the ${position} position of the left column so it sits in the natural reading path.`
          : isResults
            ? "Results panel — given equal width as the Method because quantitative comparisons are the most-cited part of any paper."
            : `Section panel extracted from page ${brief?.sections[idx]?.pageStart ?? "?"} of the source PDF. Text truncated to 400 chars to keep the panel readable from across a conference hall.`,
      }
    }
    case "figure": {
      const caption = attrs["data-figure-caption"] ?? "Figure"
      const page = attrs["data-figure-page"] ?? "?"
      return {
        title: "Figure placeholder",
        body: `Original figure from page ${page} of the PDF could not be embedded automatically — the placeholder shows the caption "${caption}" instead. Click "Edit" in the toolbar to upload a replacement image.`,
      }
    }
    case "claim": {
      const text = attrs["data-claim-text"] ?? ""
      const page = attrs["data-claim-page"] ?? "?"
      return {
        title: "Key claim",
        body: `Extracted from page ${page} of the source paper by matching strong verbs (show, demonstrate, achieve, outperform, propose, introduce, present, report) in sentences between 30–400 characters. Original claim: "${text.slice(0, 120)}${text.length > 120 ? "…" : ""}"`,
      }
    }
    case "claims":
      return {
        title: "Claims block",
        body: "Container for the top 3 claims ranked by importance (primary first). Extracted with the verb-matching heuristic described in the claim entries.",
      }
    case "table": {
      const caption = attrs["data-table-caption"] ?? "Table"
      return {
        title: "Table reference",
        body: `Detected table "${caption}" from the source PDF. Cell-by-cell extraction is on the roadmap; for now, this panel links back to the page reference so readers can find the full table in the paper.`,
      }
    }
    default:
      return {
        title: "Panel",
        body: "No reasoning recorded for this element.",
      }
  }
}
